Giorno_1/Esercitazione_M5_Seconda_Settimana/Controllers/AuthController.cs
using Esercitazione_M5_Seconda_Settimana.Models;
using Esercitazione_M5_Seconda_Settimana.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Esercitazione_M5_Seconda_Settimana.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;

        public AuthController(IAuthService authService)
        {
            _authService = authService;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(Users u)
        {
            try
            {
                var user = _authService.Login(u.Username, u.Password);
                if (user == null)
                {
                    return RedirectToAction("Register");
                }
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, u.Username)
                };

                var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(identity));
            }
            catch (Exception ex) { }
            return RedirectToAction("GetAllPrenotazioni", "Prenotazioni");
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]

        public IActionResult Register(Users u)
        {
            try
            {
                var user = _authService.Register(u.Username, u.Password);
            }
            catch (Exception ex) { }
            return RedirectToAction("Login");
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Login");
        }
    }
}

Giorno_1/Esercitazione_M5_Seconda_Settimana/Controllers/CamereController.cs
using Esercitazione_M5_Seconda_Settimana.Models;
using Esercitazione_M5_Seconda_Settimana.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Esercitazione_M5_Seconda_Settimana.Controllers
{
    [Authorize]
    public class CamereController : Controller
    {
        private ICamereService _camereService;

        public CamereController(ICamereService camereService)
        {
            _camereService = camereService;
        }
        public IActionResult CreaCamera()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreaCamera(Camera camera)
        {
            var c = _camereService.CreaCamera(camera);
            return RedirectToAction("Index", "Home");
        }
    }
}

Giorno_1/Esercitazione_M5_Seconda_Settimana/Controllers/ClientiController.cs
using Esercitazione_M5_Seconda_Settimana.Models;
using Esercitazione_M5_Seconda_Settimana.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Esercitazione_M5_Seconda_Settimana.Controllers
{
    [Authorize]
    public class ClientiController : Controller
    {
        private IClientiService _clientiservice;

        public ClientiController(IClientiService clientiService)
        {
            _clientiservice = clientiService;
        }
        public IActionResult CreaCliente()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreaCliente(Cliente cliente)
        {
            var c = _clientiservice.CreaCliente(cliente);
            return RedirectToAction("Index", "Home");
        }
    }
}

Giorno_1/Esercitazione_M5_Seconda_Settimana/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Esercitazione_M5_Seconda_Settimana</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Esercitazione_M5_Seconda_Settimana.styles.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light myBgPurple border-bottom box-shadow mb-3">
            <div class="container-fluid d-flex justify-content-between align-items-center px-4">
                <a class="navbar-brand text-white fs-3 fw-bold" asp-area="" asp-controller="Prenotazioni" asp-action="GetAllPrenotazioni">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between align-items-center">
                    <ul class="navbar-nav flex-grow-1 d-flex justify-content-between align-items-center">
                        @if (User.Identity.IsAuthenticated)
                        {   <div class="d-flex">
                                <div class="dropdown">
                                    <button class="btn dropdown-toggle text-white" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                        Azioni Creazione
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">


                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Prenotazioni" asp-action="CreazionePrenotazione">Crea Prenotazione</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Camere" asp-action="CreaCamera">Crea Camere</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Clienti" asp-action="CreaCliente">Crea Cliente</a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="dropdown">
                                    <button class="btn dropdown-toggle text-white" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                        Azioni Cerca
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Prenotazioni" asp-action="CercaByCf">Cerca CF</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Prenotazioni" asp-action="CercaByPensione">Cerca Pensione</a>
                                        </li>
                                    </ul>
                                </div>    
                            </div>
                            <a class="nav-link text-white" asp-area="" asp-controller="Auth" asp-action="Logout">Esci</a>
                            
                        }
                      
                    </ul>
                </div>
                @if(!User.Identity.IsAuthenticated)
                {
                <a class="nav-link text-white" asp-area="" asp-controller="Auth" asp-action="Login">Accedi</a>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>