Giorno_1/Esercitazione_M5_Seconda_Settimana/Controllers/PrenotazioniController.cs
using Esercitazione_M5_Seconda_Settimana.Models;
using Esercitazione_M5_Seconda_Settimana.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Esercitazione_M5_Seconda_Settimana.Controllers
{
    [Authorize]
    public class PrenotazioniController : Controller
    {
        private IPrenotazioneService _prenotazioneService;
        public PrenotazioniController(IPrenotazioneService prenotazioneService)
        {
            _prenotazioneService = prenotazioneService;
        }
        public IActionResult CreazionePrenotazione()
        {
            return View();
        }
        public IActionResult GetAllPrenotazioni()
        {
            var p = _prenotazioneService.GetAll();
            return View(p);
        }

        public IActionResult Checkout(int id)
        {
            ViewBag.Id = id;
            var p = _prenotazioneService.Checkout(id);
            return View(p);
        }

        [HttpPost]
        public IActionResult CreazionePrenotazione(Prenotazione p)
        {
            var prenotazione = _prenotazioneService.CreaPrenotazione(p);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult CreaPrenotazioneServizio()
        {
            ViewBag.servizi = _prenotazioneService.GetServizi();
            return View();
        }

        [HttpPost]
        public IActionResult CreaPrenotazioneServizio(PrenotazioniServizio p, int id)
        {
            var prenotazione = _prenotazioneService.CreaPrenotazioneServizio(p, id);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult CercaByCf()
        {
            return View();
        }

        public IActionResult CercaByPensione()
        {
            return View();
        }



    }
}

Giorno_1/Esercitazione_M5_Seconda_Settimana/Views/Prenotazioni/CercaByCf.cshtml
<div class="container">
    <h1 class="text-center">Lista prenotazioni per C.F</h1>

    <div class="form-group mt-4">
        <label for="cf" class="control-label mb-1 ps-2">Inserisci il C.F per visualizzarne le prenotazioni:</label>
        <div class="d-flex mt-2">
            <input type="text" id="cf" name="cf" class="form-control qnt me-2">
            <button class="btn myBtn" id="searchButton">Cerca</button>
        </div>
    </div>

    <div class="row justify-content-center" id="prenotazioniContainer" class="mt-5">
    </div>
</div>

Giorno_1/Esercitazione_M5_Seconda_Settimana/Views/Prenotazioni/CercaByPensione.cshtml
<div class="container">
    <h1 class="text-center">Lista prenotazioni per pensione</h1>

    <div class="form-group mt-4">
        <label for="pensione" class="control-label mb-1 ps-2">Scegli il tipo di pensione per visualizzarne le prenotazioni:</label>
        <div class="d-flex mt-2">
            <select id="pensione" class="form-control me-2 qnt">
                <option value="" disabled selected>Seleziona pensione</option>
                <option value="Prima Colazione">Prima Colazione</option>
                <option value="Mezza Pensione">Mezza Pensione</option>
                <option value="Pensione Completa">Pensione Completa</option>
            </select>
            <button class="btn myBtn" id="searchButtonP">Cerca</button>
        </div>
    </div>

    <div class="row justify-content-center" id="prenotazioniContainer" class="mt-3">
    </div>
</div>

Giorno_1/Esercitazione_M5_Seconda_Settimana/Views/Prenotazioni/Checkout.cshtml
@model Esercitazione_M5_Seconda_Settimana.Models.AllModels.AllModels

@{
    ViewData["Title"] = "Checkout";
    var id = ViewBag.Id;
}

<h1 class="ps-2 mb-2">Checkout</h1>

        <div class="card card-custom">
            <div class="card-header-custom">
                Dettagli della Prenotazione ID: @id
            </div>
            <div class="card-body card-body-custom">
                <dl class="row dl-horizontal">
                    <dt class="col-sm-3">Numero Camera:</dt>
                    <dd class="col-sm-9">@Html.DisplayFor(model => model.Prenotazione.NumCamera)</dd>

                    <dt class="col-sm-3">Data Inizio Soggiorno:</dt>
                    <dd class="col-sm-9">@Html.DisplayFor(model => model.Prenotazione.SoggiornoDal)</dd>

                    <dt class="col-sm-3">Data Fine Soggiorno:</dt>
                    <dd class="col-sm-9">@Html.DisplayFor(model => model.Prenotazione.SoggiornoAl)</dd>

                    <dt class="col-sm-3">@Html.DisplayNameFor(model => model.Prenotazione.Tariffa)</dt>
                    <dd class="col-sm-9">€@Html.DisplayFor(model => model.Prenotazione.Tariffa)</dd>
                </dl>
            </div>
        </div>

        <div class="card card-custom mt-3">
            <div class="card-header-custom">
                Servizi Aggiuntivi
            </div>
            <div class="card-body card-body-custom">
                @if (Model.Servizio != null && Model.Servizio.Any())
                {
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Quantità</th>
                                <th>@Html.DisplayNameFor(model => model.Servizio.First().Descrizione)</th>
                                <th>Prezzo Singolo Servizio</th>
                                <th>Prezzo Totale</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var servizio in Model.Servizio)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => servizio.Quantita)</td>
                                    <td>@Html.DisplayFor(modelItem => servizio.Descrizione)</td>
                                    <td>€@Html.DisplayFor(modelItem => servizio.Prezzo)</td>
                                    <td>€@Html.DisplayFor(modelItem => servizio.PrezzoTot)</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <p>Nessun servizio aggiunto.</p>
                }
            </div>
        </div>

        <div class="card card-custom mt-3">
            <div class="card-header-custom">
                Importo
            </div>
            <div class="card-body card-body-custom">
                <dl class="row dl-horizontal">
                    <dt class="col-sm-3">Importo Totale:</dt>
                    <dd class="col-sm-9">€@Html.DisplayFor(model => model.Importo)</dd>
                </dl>
            </div>
        </div>

Giorno_1/Esercitazione_M5_Seconda_Settimana/Views/Prenotazioni/CreaPrenotazioneServizio.cshtml
@model Esercitazione_M5_Seconda_Settimana.Models.PrenotazioniServizio

@{
    ViewData["Title"] = "Crea Prenotazione Servizio";
    var servizi = ViewBag.servizi as List<Servizio>;
}

<div class="row justify-content-center">
    <div class="col-md-6">
        <h1 class="text-center">Aggiungi servizio alla prenotazione</h1>

        <hr class="myBgPurple"/>
        <form asp-action="CreaPrenotazioneServizio">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group mt-3">
                <label asp-for="IdServizio" class="control-label mb-1 ps-2">Seleziona un servizio:</label>
                <select asp-for="IdServizio" class="form-control qnt">
                    <option value="" disabled selected>Seleziona un servizio</option>
                    @foreach (var s in servizi)
                    {
                        <option value="@s.IdServizio">@s.Descrizione</option>
                    }
                </select>
                <span asp-validation-for="IdServizio" class="text-danger"></span>
            </div>

            <div class="form-group mt-3">
                <label asp-for="Data" class="control-label mb-1 ps-2">Inserisci data:</label>
                <input asp-for="Data" class="form-control qnt" />
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>

            <div class="form-group mt-3">
                <label asp-for="Quantita" class="control-label mb-1 ps-2">Inserisci quantità:</label>
                <input asp-for="Quantita" class="form-control qnt" />
                <span asp-validation-for="Quantita" class="text-danger"></span>
            </div>

            <div class="form-group mt-3">
                <label asp-for="Prezzo" class="control-label mb-1 ps-2">Inserisci prezzo <span class="fw-bolder">(€)</span> :</label>
                <input asp-for="Prezzo" class="form-control qnt" />
                <span asp-validation-for="Prezzo" class="text-danger"></span>
            </div>

            <div class="form-group mt-3">
                <input type="submit" value="Crea" class="btn myBtn" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Giorno_1/Esercitazione_M5_Seconda_Settimana/Views/Prenotazioni/CreazionePrenotazione.cshtml
@model Esercitazione_M5_Seconda_Settimana.Models.Prenotazione

@{
    ViewData["Title"] = "Aggiunta Prenotazione";
}


<div class="row justify-content-center">
    <div class="col-md-6">
        <h1 class="text-center">Crea Prenotazione</h1>

        <hr class="myBgPurple"/>
        <form asp-action="CreazionePrenotazione">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DataPrenotazione" class="control-label mb-1 ps-2">Inserisci data prenotazione:</label>
                <input asp-for="DataPrenotazione" class="form-control qnt" />
                <span asp-validation-for="DataPrenotazione" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <label asp-for="NumProgressivo" class="control-label mb-1 ps-2">Inserisci num. progressivo:</label>
                <input asp-for="NumProgressivo" class="form-control qnt" />
                <span asp-validation-for="NumProgressivo" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <label asp-for="Anno" class="control-label mb-1 ps-2">Inserisci anno:</label>
                <input asp-for="Anno" class="form-control qnt" />
                <span asp-validation-for="Anno" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <label asp-for="SoggiornoDal" class="control-label mb-1 ps-2">Inserisci data inizio soggiorno:</label>
                <input asp-for="SoggiornoDal" class="form-control qnt" />
                <span asp-validation-for="SoggiornoDal" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <label asp-for="SoggiornoAl" class="control-label mb-1 ps-2">Inserisci data fine soggiorno:</label>
                <input asp-for="SoggiornoAl" class="form-control qnt" />
                <span asp-validation-for="SoggiornoAl" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <label asp-for="Caparra" class="control-label mb-1 ps-2">Inserisci caparra <span class="fw-bolder">(€)</span>:</label>
                <input asp-for="Caparra" class="form-control qnt" />
                <span asp-validation-for="Caparra" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <label asp-for="Tariffa" class="control-label mb-1 ps-2">Inserisci tariffa <span class="fw-bolder">(€)</span>:</label>
                <input asp-for="Tariffa" class="form-control qnt" />
                <span asp-validation-for="Tariffa" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <label asp-for="PensioneCompleta" class="control-label mb-1 ps-2">Inserisci tipo pensione:</label>
                <select asp-for="PensioneCompleta" class="form-control qnt">
                    <option value="" disabled selected>Seleziona una opzione</option>
                    <option value="Prima Colazione">Prima Colazione</option>
                    <option value="Mezza Pensione">Mezza Pensione</option>
                    <option value="Pensione Completa">Pensione Completa</option>
                </select>
                <span asp-validation-for="PensioneCompleta" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <label asp-for="IdCliente" class="control-label mb-1 ps-2">Inserisci identificativo cliente:</label>
                <input asp-for="IdCliente" class="form-control qnt" />
                <span asp-validation-for="IdCliente" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <label asp-for="IdCamera" class="control-label mb-1 ps-2">Inserisci identificativo camera:</label>
                <input asp-for="IdCamera" class="form-control qnt" />
                <span asp-validation-for="IdCamera" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Crea" class="btn myBtn" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Giorno_1/Esercitazione_M5_Seconda_Settimana/Views/Prenotazioni/GetAllPrenotazioni.cshtml
@model IEnumerable<Esercitazione_M5_Seconda_Settimana.Models.Prenotazione>

@{
    ViewData["Title"] = "Lista Prenotazioni";
}


<div class="container">
    <h1 class="text-center">Lista Prenotazioni</h1>
    <div class="row justify-content-center">
        <table class="table mt-4 myBorder text-center">
            <thead>
                <tr class="myBorder text-nowrap">
                    <th class="border-bottom-0 p-2">Id. Prenotazione</th>
                    <th class="border-bottom-0 p-2">Data Prenotazione</th>
                    <th class="border-bottom-0 p-2">Num. Progressivo</th>
                    <th class="border-bottom-0 p-2">@Html.DisplayNameFor(model => model.Anno)</th>
                    <th class="border-bottom-0 p-2">Data Inizio Soggiorno</th>
                    <th class="border-bottom-0 p-2">Data Fine Soggiorno</th>
                    <th class="border-bottom-0 p-2">@Html.DisplayNameFor(model => model.Caparra)</th>
                    <th class="border-bottom-0 p-2">@Html.DisplayNameFor(model => model.Tariffa)</th>
                    <th class="border-bottom-0 p-2">Tipo Pensione</th>
                    <th class="border-bottom-0 p-2">Id. Cliente</th>
                    <th class="border-bottom-0 p-2">Id. Camera</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="text-nowrap">
                        <td class="py-3">@Html.DisplayFor(modelItem => item.IdPrenotazione)</td>
                        <td class="py-3">@Html.DisplayFor(modelItem => item.DataPrenotazione)</td>
                        <td class="py-3">@Html.DisplayFor(modelItem => item.NumProgressivo)</td>
                        <td class="py-3">@Html.DisplayFor(modelItem => item.Anno)</td>
                        <td class="py-3">@Html.DisplayFor(modelItem => item.SoggiornoDal)</td>
                        <td class="py-3">@Html.DisplayFor(modelItem => item.SoggiornoAl)</td>
                        <td class="py-3">@Html.DisplayFor(modelItem => item.Caparra)</td>
                        <td class="py-3">@Html.DisplayFor(modelItem => item.Tariffa)</td>
                        <td class="py-3">@Html.DisplayFor(modelItem => item.PensioneCompleta)</td>
                        <td class="py-3">@Html.DisplayFor(modelItem => item.IdCliente)</td>
                        <td class="py-3">@Html.DisplayFor(modelItem => item.IdCamera)</td>
                        <td class="py-3">
                            <a class="myBtn" asp-controller="Prenotazioni" asp-action="Checkout" asp-route-id="@item.IdPrenotazione">Checkout</a>
                        </td>
                        <td class="py-3">
                            <a class="myBtnTwo" asp-controller="Prenotazioni" asp-action="CreaPrenotazioneServizio" asp-route-id="@item.IdPrenotazione">Aggiungi Servizi</a>
                        </td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
</div>